### ISSUE TITLE
No Config options 

### ISSUE THREAD

**Issue by mathiasuhl** [tcarlsen/atom-csslint#12]
CSSLint is hardly usable without the proper config setting. Well I can't see an option for global config yet. It would be great if this would be added.

**Comment by tcarlsen** [comment]
add a  `.csslintrc` file in your project for project related settings, create a `.csslintrc` file in you HOME environment for global settings

**Comment by BMOv2600** [comment]
Is there a demo of a working .csslintrc file you could please share? Either the code or the file. Mine has no effect on this package.

**Comment by tcarlsen** [comment]
take a look at the one over at bootstrap: https://github.com/twbs/bootstrap/blob/master/less/.csslintrc
