### ISSUE TITLE
Keybinding seems to be buggy

### ISSUE THREAD

**Issue by iGadget73** [tcarlsen/atom-csslint#13]
If you copy the keybinding you get this:
'atom-text-editor[data-grammar='source css']':
  'ctrl-alt-l': 'csslint:lint'

but it should NOT use single quotes for data-grammar value. should be
'atom-text-editor[data-grammar="source css"]':
  'ctrl-alt-l': 'csslint:lint'

**Comment by tcarlsen** [comment]
Thx for reporting

**Comment by tcarlsen** [comment]
in [csslint.cson](https://github.com/tcarlsen/atom-csslint/blob/master/keymaps/csslint.cson) there is double quotes outside

```cson
  "atom-text-editor[data-grammar='source css']":
    "ctrl-alt-l": "csslint:lint"
```
