### ISSUE TITLE
Use the linter package for visualizations

### ISSUE THREAD

**Issue by steelbrain** [tcarlsen/atom-csslint#15]
Your package looks great, but it's re-inventing the wheel. I suggest you use linter for message visualization.

**Comment by tcarlsen** [comment]
I dont get how this is "re-inventing the wheel", now that this package was one of the first linter packages for Atom and linter did't exist back then this was created.

That aside, why should I transfrom to use linter then there already is a [csslint](https://atom.io/packages/linter-csslint) package for linter?

Lastly I think its fine to have both packages, some will like the way linter shows errors, other the way atom-message-panel does. *(Im one of them)*

**Comment by steelbrain** [comment]
The choice is yours, but we have quite a few cool features like lintOnFly and scopes like line, file and project.
