### ISSUE TITLE
errors don't go away after they're fixed

### ISSUE THREAD

**Issue by stitchinspace** [tcarlsen/atom-csslint#18]
I love this plugin!

Ideally error messages would go away after I fix them and save, but they just keep piling up. 

This isn't a bug, but related: I would like to be able to 'ignore' individual messages as well, especially warnings.

Thank you!

**Comment by tcarlsen** [comment]
I really can't replicate this issue

![](http://g.recordit.co/9Afk9yz23B.gif)

If you want to ignore some rules you need a `.csslintrc` file like this: https://github.com/ebednarz/csslintrc/blob/master/.csslintrc

**Comment by stitchinspace** [comment]
Hi Thomas,
Thanks for checking this out. Here are some screen shots of what I mean. In
this example the warning at the bottom of the page for line 13 persists
after I change the selector from '#' to '.'

I appreciate your suggestion to edit my personal CSSLint settings, however
after doing as much digging and fiddling as I was comfortable doing I
didn't figure out how. If you could quickly point me toward some resources
for learning about this I would appreciate it, but don't worry about it.
I'm sure I will learn these sort of things along the way.

stitch

[image: Inline image 3]


[image: Inline image 4]

**Comment by tcarlsen** [comment]
I cant see your images???

heres the csslint wiki for all of the rules. maybe that will help you out?
https://github.com/CSSLint/csslint/wiki/rules
