### ISSUE TITLE
Explain where global .csslintrc file should be

### ISSUE THREAD

**Issue by yamboy1** [tcarlsen/atom-csslint#21]
You should explain in your readme, where the global .csslintrc file goes. I only figured it out by looking at the source, and a lot of people probably won't do that.

**Comment by tcarlsen** [comment]
I do agree that it could help some people, but the global `.csslintrc` file location will differ from system to system and your setup? So should I write the default location on all systems? (linux/macOS/windows)?

THis is not me saying no, but looking for the best way to do this 😄

**Comment by yamboy1** [comment]
Can't you just say that it should be saved in the users home directory, because it looks like it's looking in there for the `.csslintrc`

**Comment by tcarlsen** [comment]
fixed in #22
