### ISSUE TITLE
Running csslint while typing

### ISSUE THREAD

**Issue by PiJoules** [tcarlsen/atom-csslint#8]
How can I have csslint check over the code while I am typing? I am new to atom and am unsure how to change package settings on atom.

Thanks in advance.

**Comment by tcarlsen** [comment]
1. go to Settings `->` Packages
2. use ther filter to search for `csslint``
3. hit the Settings on `csslint`
4. toggle the "Validate On Save" checkbox

:dancer:

**Comment by PiJoules** [comment]
Thanks, got it working.
